### ISSUE TITLE
repeated code?

### ISSUE THREAD

**Issue by FeiGSSS** [hilbert9221/NRI-MPM#1]
In the test function, is this [line](https://github.com/hilbert9221/NRI-MPM/blob/d2cb7a36e035be8fe4a453cfb31004e38073b41b/instructors/XNRI.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L181) redundancy?

**Comment by hilbert9221** [comment]
Sorry for replying too late. Line 181 is not redundant. The returned variable `output` is used to compute the MSEs for multi-step prediction, essentially the metrics reported in our paper and [NRI](https://github.com/ethanfetaya/NRI). Maybe the variables `loss/losses` (Line 168-169) and `mse/mse_multi` (Line 184-195) confuse you for their names and similar computation. I realize that variables `loss/losses` may be redundant for the testing stage. I would consider removing relevant codes.

Thank you for pointing out this problem!
